# Generated by Django 4.1 on 2023-10-27 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customer",
            table="accounts_customer",
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="accounts_custom_user",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="accounts_employee",
        ),
    ]
