# Generated by Django 4.1.13 on 2023-11-17 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_alter_customuser_options_alter_customer_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employé", "verbose_name_plural": "Employés"},
        ),
    ]
