# Generated by Django 4.1 on 2023-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
