# Generated by Django 4.1 on 2023-10-26 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0002_alter_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 26, 16, 3, 8, 949141)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 26, 16, 3, 8, 949141)
            ),
        ),
    ]
