# Generated by Django 4.1 on 2023-10-27 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0003_alter_discount_end_date_alter_discount_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 27, 19, 23, 23, 208601)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 27, 19, 23, 23, 208601)
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="catalog_category",
        ),
        migrations.AlterModelTable(
            name="discount",
            table="catalog_discount",
        ),
        migrations.AlterModelTable(
            name="product",
            table="catalog_product",
        ),
    ]
