# Generated by Django 4.1 on 2023-10-27 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0004_alter_discount_end_date_alter_discount_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 27, 19, 27, 3, 757214)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 27, 19, 27, 3, 757214)
            ),
        ),
    ]
