# Generated by Django 4.1 on 2023-10-28 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0005_alter_discount_end_date_alter_discount_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 19, 7, 41, 831321)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 19, 7, 41, 831321)
            ),
        ),
    ]
