# Generated by Django 4.1 on 2023-10-28 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0006_category_subcategory_alter_discount_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategory",
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 19, 10, 24, 802027)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 19, 10, 24, 802027)
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="subcategory",
            field=models.ManyToManyField(to="Catalog.category"),
        ),
    ]
