# Generated by Django 4.1 on 2023-10-28 17:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "Catalog",
            "0007_remove_category_subcategory_alter_discount_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 19, 29, 41, 948112)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 19, 29, 41, 948112)
            ),
        ),
    ]
