# Generated by Django 4.1 on 2023-10-29 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0009_alter_category_parent_alter_discount_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 29, 13, 7, 46, 689230)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 29, 13, 7, 46, 689230)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products", to="Catalog.category"
            ),
        ),
    ]
