# Generated by Django 4.1 on 2023-11-12 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0016_alter_discount_end_date_alter_discount_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 12, 16, 12, 26, 404515)
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 12, 16, 12, 26, 404515)
            ),
        ),
    ]
