# Generated by Django 4.1.13 on 2023-11-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Catalog", "0020_alter_category_icon_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catégorie", "verbose_name_plural": "Catégories"},
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name": "Promotion", "verbose_name_plural": "Promotions"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="Catalog.category",
                verbose_name="Catégorie parente",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateField(verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Remise"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateField(verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products",
                to="Catalog.category",
                verbose_name="Catégories",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Catalog.discount",
                verbose_name="Promotion",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix de base"
            ),
        ),
    ]
