# Generated by Django 4.1 on 2023-10-27 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="stores_company",
        ),
        migrations.AlterModelTable(
            name="country",
            table="stores_country",
        ),
        migrations.AlterModelTable(
            name="store",
            table="stores_stores",
        ),
    ]
