# Generated by Django 4.1.13 on 2023-11-17 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Stores", "0002_alter_company_table_alter_country_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Pays", "verbose_name_plural": "Pays"},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"verbose_name": "Magasin", "verbose_name_plural": "Magasins"},
        ),
    ]
